from typing import List, Dict, TypedDict
from langchain_google_genai import ChatGoogleGenerativeAI
from tavily import TavilyClient
from pydantic import BaseModel, Field
from dotenv import load_dotenv
load_dotenv()

class ResearchState(TypedDict):
    topic: str                  # The original overarching query
    sub_queries: List[str]      # Split queries generated by the LLM
    search_results: List[Dict]  # Aggregated articles and snippets
    analysis: str               # Mid-point synthesis 
    report: str                 # Final markdown compilation


llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

# Enforce a strict structure for the planner's output
class QueryList(BaseModel):
    queries: List[str] = Field(description="List of 3 to 5 targeted search queries.")

planner_llm = llm.with_structured_output(QueryList)

# Plan the queries 
def plan_queries_node(state: ResearchState):
    prompt = f"""You are an expert research planner. Given the topic: '{state['topic']}', 
    break it down into 3-5 distinct, targeted sub-queries to gather comprehensive web data."""
    
    response = planner_llm.invoke(prompt)
    return {"sub_queries": response.queries}

# Use Tavily to get search results
def get_search_results(state:ResearchState):
    tavily_client = TavilyClient() 
    for query in state["sub_queries"]:
     response = tavily_client.search(
     query=query,
     search_depth="advanced",
     max_results=3
    )
    # print(response)
    return {'search_results':response}

def analyze s