from typing import List, Dict, TypedDict
from pydantic import BaseModel, Field

class ResearchState(TypedDict):
    topic: str                  # The original overarching query
    sub_queries: List[str]      # Split queries generated by the LLM
    search_results: List[Dict]  # Aggregated articles and snippets
    analysis: str               # Mid-point synthesis 
    report: str                 # Final markdown compilation

# Enforce a strict structure for the planner's output
class QueryList(BaseModel):
    queries: List[str] = Field(description="List of 3 to 5 targeted search queries.")
